### PR TITLE
Add context to error messages.

### PR DESCRIPTION
**Pull request by cmarqu**
References #1017.
Needs to be expanded to other files if this is the way to go.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can we just use the functions from `gpilog`, which emulate the default python logging format if the python logger isn't yet hooked up?

**Comment by cmarqu** [comment]
I'll try, but my C is pretty rusty.

**Comment by cmarqu** [comment]
Using ``LOG_ERROR`` worked for ``gpi_embed.c`` and I was able to test two places to get the nice error output. But raw ``fprintf`` is also used in other places where it might be harder to check if using the macros does the right thing, so it's a bit risky unless more testing is done.

**Comment by cmarqu** [comment]
I guess printing context of errors in one more file is already an improvement, so I'll submit this as a PR in its current form.

**Comment by cmarqu** [comment]
Triggering Travis by closing/reopening.

**Comment by eric-wieser** [comment]
> where it might be harder to check whether using the macros does the right thing, so it's a bit risky unless more testing is done.

If this is something we're really worried about, one option in a future PR would be to add an environment variable which means "log to stderr directly as well as through the python logging". I think we should work on the assumption that `LOG_ERROR` and friends work correctly. and cross that bridge when we get to it.

**Comment by themperek** [comment]
Thank you.

**Comment by eric-wieser** [comment]
> and cross that bridge when we get to it.

That happened embarrassingly soon (gh-1086)

**Pull request merged**
