### PR TITLE
Update Python versions in CI

### PR DESCRIPTION
**Pull request by imphil**
* Run lint on the latest Python release
* Add a test for the upcoming Python version

### CODE REVIEW

**Comment by imphil** [comment]
I'll have a closer look tomorrow, need to get a Python 3.11 version locally first.

**Comment by marlonjames** [comment]
This works on Python 3.8, but fails on 3.11:
```py3
l = [(None, 2), (None, 1)]
l.sort()
```
`stage` defaults to `None`, causing the issue in 3.11
https://github.com/cocotb/cocotb/blob/cffafa91f380158ca9ba612aec81f77a0d60ae35/cocotb/decorators.py#L443-L452
Tests are sorted here:
https://github.com/cocotb/cocotb/blob/cffafa91f380158ca9ba612aec81f77a0d60ae35/cocotb/regression.py#L139

**Comment by ktbarrett** [comment]
@marlonjames Seems like we could just change the default to 0 then?

**Comment by imphil** [comment]
One down, more to go:


```
   /home/runner/work/cocotb/cocotb/tests/test_cases/test_cocotb/test_scheduler.py:665: RuntimeWarning: coroutine 'test_create_task.<locals>.coro' was never awaited
    assert type(cocotb.create_task(coro())) == RunningTask
  RuntimeWarning: Enable tracemalloc to get the object allocation traceback
  /home/runner/work/cocotb/cocotb/tests/test_cases/test_cocotb/test_scheduler.py:684: RuntimeWarning: coroutine 'test_create_task.<locals>.coro' was never awaited
    assert type(cocotb.create_task(CoroType())) == RunningTask
  RuntimeWarning: Enable tracemalloc to get the object allocation traceback
  SCHEDULER ERROR: read-only sync events created RW events!
  sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>
  ResourceWarning: Enable tracemalloc to get the object allocation traceback
  ```

Seems like this early testing is worthwhile :-)

**Comment by ktbarrett** [comment]
The `stage` change in default to `0` and remove support for `None` fixes a bug where if you mix tests setting stage and not setting stage it breaks because comparison of `None` and and int. It's very likely that the `stage` feature could be removed and no one would miss it.

**Comment by ktbarrett** [comment]
Looks like tests which test the traceback by string are failing. I will change those tests to not do that. Those tests need to go.

**Comment by eric-wieser** [comment]
Regarding traceback strings, I'd lean towards:
* Adding the missing `^` lines included in new python versions to the matches
* Stripping out those lines before doing the match if the python version is too old

Sure, checking the traceback data structure would be less fragile, but it's also more work and makes it harder to read the test.

**Comment by ktbarrett** [comment]
Can you justify those tests? What are they actually testing? Traceback output *is not a stable API*. Seems to me you are needlessly creating work.

**Comment by ktbarrett** [comment]
The traceback tests will be fixed instead by what is mentioned in https://github.com/cocotb/cocotb/pull/2865#issuecomment-1043297331. This will continue testing the traceback, but in a less fragile way.

**Review by cmarqu — APPROVED** [review]

**Review by ktbarrett — APPROVED** [review]

**Comment by imphil** [comment]
Rebased on top of master with the nox changes.

**Comment by imphil** [comment]
The GHDL nightly fail is due to a missing apt-get update before installing packages in the relevant GH action, which will be resolved once they do a new release (fixed as of an hour ago: https://github.com/ghdl/setup-ghdl-ci/commit/d1153380e62073d4d426b0627fea21fe9bf8d784)

**Pull request merged**
