### PR TITLE
Update docs to use the `sig.value = value` syntax

### PR DESCRIPTION
**Pull request by cmarqu**
Refs #2667.

### CODE REVIEW

**Comment by cmarqu** [comment]
The same change in `quickstart.rst` will come in via #2710.

**Review by ktbarrett — APPROVED** [review]
Looks good. I think in addition to updating the quickstart we will need to scrub the docstrings as well.

**Comment by cmarqu** [comment]
My grepping didn't find any docstrings to fix, just two comments and one additional occurrence in code.
Did you see a docstring that needed fixing?

**Comment by ktbarrett** [comment]
Looks like I fixed the ones I'm thinking about in #2667.

**Pull request merged**
