### PR TITLE
Fix wrong vhpi library name for ius and aldec in v1.3

### LINKED ISSUE #1459: libcocotbvhpi.dll" library. The library does not exist or is corrupted
I am working with pyhton 3.7, Aldec Riviera Pro 2017- 64-bit, cocotb 1.3 and MSYS2. When I run this test on jenkins and on remote PC I'm getting getting this issue. 

My log looks like this:

VHPI: Loading library 'C:/JenkinsSlave/workspace/Regression_Tests_CoCoTB_mao/Vivado/ip_repo/registers_1.0/sim/build/libs/x86_64/libcocotbvhpi.dll'
VHPI: Cannot load the "C:/JenkinsSlave/workspace/Regression_Tests_CoCoTB_mao/Vivado/ip_repo/registers_1.0/sim/build/libs/x86_64/libcocotbvhpi.dll" library. The library does not exist or is corrupted.

Solution tried so far: 
1. checked if the file is there and checked the dependencies of the dll file as well. (all good) 
2. Discovered Riviera has its own gcc version which is different from MSYS2 (mingw64) --not sure if that is a problem ? 
3. Played with PATH in environment variables (didn't work clearly)

Any suggestions will be helpful. I am really stuck at the moment. Thanks in advance!

### PR DESCRIPTION
**Pull request by themperek**
Resolves #1459

### CODE REVIEW

**Comment by themperek** [comment]
@cmarqu Maybe one should add some release note?

**Comment by eric-wieser** [comment]
towncrier wasn't part of 1.3.x, so you'd need to modify the release note file directly.

**Comment by cmarqu** [comment]
> @cmarqu Maybe one should add some release note?

Could you pick the text from https://github.com/cocotb/cocotb/pull/1474/files (provided there are no other wording suggestions)?

**Comment by themperek** [comment]
CI fails on windows due to Travis changes: Could patch with https://github.com/cocotb/cocotb/commit/43e78dd32b3b2d241d83dc346d81d9a5727f8d35 and https://github.com/cocotb/cocotb/commit/39371f4ea6092fb4eab00c982360170ea8b11f8f

**Comment by themperek** [comment]
@imphil Could you check if this is ok?

**Comment by imphil** [comment]
I updated this PR to 
- Remove the update of the version number and the release date as part of the backport.
- Do a full backport of the commit using `git cherry-pick`

CI is green, so let's merge it and start the release process.

**Pull request merged**
