### PR TITLE
Various formatting changes

### PR DESCRIPTION
**Pull request by Matthewar**
Small change I noticed, and made some other formatting fixes (removing trailing whitespace, use of percentages in logging calls)
- Unnecessary variable assignment before carrying out the same operation in a return statement: https://github.com/potentialventures/cocotb/compare/master...Matthewar:handle_fix?expand=1#diff-4da3213e60c3436d11d6e573a6104889L263
- Unused imports: https://github.com/potentialventures/cocotb/compare/master...Matthewar:handle_fix?expand=1#diff-4da3213e60c3436d11d6e573a6104889L32

### CODE REVIEW

**Comment by imphil** [comment]
How much of that is still needed after the other PR? Can you rebase/close as needed?

**Comment by Matthewar** [comment]
I'm pretty sure this touches different files, and fixes a small inefficiency from duplicated code. Will handle that conflict though by merging in master.

**Comment by Matthewar** [comment]
Actually, the variable assignment was fixed in commit https://github.com/potentialventures/cocotb/commit/5ecc1f850c140e576c16eaf1a36eeb8410edd7a5 so this is now just formatting changes, changing title - will rebase this to change commit message.

**Comment by imphil** [comment]
Please don't merge in master; rebase on top of master instead.

**Comment by Matthewar** [comment]
Yeah, I'm going to rebase this, don't worry. In my own repos I often use squash and merge instead of merge, so it was a reflex thing to merge master into here.

**Comment by eric-wieser** [comment]
Better commit message would be
```
Let the logging module perform string interpolation

Doing so avoids the cost of formatting of logging is disabled.
```

**Pull request merged**
