### PR TITLE
Fix pre-commit bump

### PR DESCRIPTION
**Pull request by ktbarrett**
More changes... this is starting to seem like more of a chore than it should be.

### CODE REVIEW

**Comment by cmarqu** [comment]
Maybe https://pypi.org/project/pre-commit-update/#pre-commit-hook-usage-example works better?

**Comment by ktbarrett** [comment]
We settled on switching to pre-commit.ci.

**Comment by ktbarrett** [comment]
We no longer need the lint action as pre-commit.ci does the same thing. pre-commit.ci should also autoupdate the dependencies. I added the `autofix_prs: false` config so that the CI wouldn't push lint fix PRs up automatically. I feel that breaks "have good commits".

**Review by imphil — APPROVED** [review]
LGTM. Pre-commit CI seems to run on this PR, so only auto-update is still to be tested.

**Pull request merged**
