### PR TITLE
Remove F741 from flake8 ignore list

### PR DESCRIPTION
**Pull request by cmarqu**
Fix occurrence of this error.
Refs #1547.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Not sure if this one is worth the churn

**Comment by imphil** [comment]
I'm OK with renaming, but a local variable with an underscore (`_len`) looks inconsistent compared to the other code. (I personally would probably continue to ignore this warning, `l` is a perfectly good variable name in my mind; but fine either way.)

**Comment by imphil** [comment]
... and please fix the commit message to say `E741` instead of `F741`.

**Comment by eric-wieser** [comment]
As an aside, the convention for avoiding name clashes with builtins is `name_` not `_name`. But I'd either pick a better name, or just leave this as `l`.

**Comment by cmarqu** [comment]
I personally wouldn't use a single-character identifier, and especially in ``utils.py`` usage of ``l`` is not restricted to within just 3 or so lines, but given that this is not our original code anyway, let's leave it at that.

**Pull request closed without merging**
