### PR TITLE
Add XCELIUM to existing IUS define checks.

### PR DESCRIPTION
**Pull request by cmarqu**
For some reason I missed to also check for the ``XCELIUM`` define when I introduced ``Makefile.xcelium``, fix that.

### CODE REVIEW

**Comment by themperek** [comment]
Is not better to just keep one in the define (across the code).

**Comment by cmarqu** [comment]
I thought about this but didn't like it so much - it then has some magic going on behind the scenes, instead of the current straightforward ``simname.upper() == DEFINE`` relation.
Also, I would expect that in the future with ghdl and Verilator getting incrementally more VPI/VHPI support, we may need to have more such switches based on both simulator names and also their versions, so the slightly more complex ``#if defined`` will not stand out much.

Of course, I'm open to change this if normalizing to a single define is the mainstream opinion.

**Comment by eric-wieser** [comment]
The normalization could happen in the c preprocessor. Is there a name that covers both of these?

**Comment by cmarqu** [comment]
``CADENCE`` would cover both.

**Comment by themperek** [comment]
Fot Qesta we keep MODELSIM do do not see what we cannot do same here.

**Comment by cmarqu** [comment]
Alright, I now used the method of the existing ModelSim/Questa normalization.

**Pull request merged**
