### PR TITLE
C++ fixes

### LINKED ISSUE #2208: Allow more than one C-level callback for a signal edge
Right now it is impossible to have more than one C-level callback for a signal edge. The issue is that we allocate the callbacks statically per signal:

https://github.com/cocotb/cocotb/blob/c4cfcd3e3faae6ea12851c0336fa92924ffce176/cocotb/share/lib/vpi/VpiImpl.h#L188-L190

I imagine this was motivated by a reluctance to implement proper memory management of these callbacks. Allocating on the heap would be a bad idea unless we were capable of cleaning up after ourselves.

Because there is only one callback, we can't afford to let C code replace the callback the currently wakes the scheduler, as doing so would make python miss events.

_Originally posted by @eric-wieser in https://github.com/cocotb/cocotb/issues/1682#issuecomment-616508278_

### PR DESCRIPTION
**Pull request by ktbarrett**
* cleanup
* don't reuse value change callback objects, allowing multiple ones to be created (closes #2208)

### CODE REVIEW

**Comment by ktbarrett** [comment]
Ugh... it's always a battle.

**Comment by ktbarrett** [comment]
So it turned out to be the fix for the memory leak that broke it.

<details>

```diff
diff --git a/src/cocotb/share/lib/gpi/GpiCommon.cpp b/src/cocotb/share/lib/gpi/GpiCommon.cpp
index 63c0da64..7be4792b 100644
--- a/src/cocotb/share/lib/gpi/GpiCommon.cpp
+++ b/src/cocotb/share/lib/gpi/GpiCommon.cpp
@@ -610,6 +610,10 @@ void gpi_deregister_callback(gpi_cb_hdl cb_hdl) {
     cb_hdl->m_impl->deregister_callback(cb_hdl);
 }
 
+void *gpi_get_callback_data(gpi_cb_hdl cb_hdl) {
+    return cb_hdl->get_user_data();
+}
+
 const char *GpiImplInterface::get_name_c() { return m_name.c_str(); }
 
 const string &GpiImplInterface::get_name_s() { return m_name; }
diff --git a/src/cocotb/share/lib/gpi/gpi_priv.h b/src/cocotb/share/lib/gpi/gpi_priv.h
index 2e4d24c7..119871a9 100644
--- a/src/cocotb/share/lib/gpi/gpi_priv.h
+++ b/src/cocotb/share/lib/gpi/gpi_priv.h
@@ -186,6 +186,7 @@ class GPI_EXPORT GpiCbHdl : public GpiHdl {
     gpi_cb_state_e get_call_state();
 
     int set_user_data(int (*function)(void *), void *cb_data);
+    void *get_user_data() { return m_cb_data; };
 
     virtual ~GpiCbHdl();
 
diff --git a/src/cocotb/share/lib/simulator/simulatormodule.cpp b/src/cocotb/share/lib/simulator/simulatormodule.cpp
index 12e2b66d..3ab4cdb8 100644
--- a/src/cocotb/share/lib/simulator/simulatormodule.cpp
+++ b/src/cocotb/share/lib/simulator/simulatormodule.cpp
@@ -764,6 +764,11 @@ static PyObject *stop_simulator(PyObject *, PyObject *) {
 }
 
 static PyObject *deregister(gpi_hdl_Object<gpi_cb_hdl> *self, PyObject *) {
+    // cleanup uncalled callback
+    auto cb = static_cast<PythonCallback *>(gpi_get_callback_data(self->hdl));
+    delete cb;
+
+    // deregister from interface
     gpi_deregister_callback(self->hdl);
 
     Py_RETURN_NONE;
```
</details>

While that does prevent a memory leak of the callback data when a callback is deregistered before it fires, it also causes a double free on that callback data if it *did* fire since we delete the callback data in both `handle_gpi_callback` after the callback is run, and in `deregister_callback` when we call it via `Trigger._unprime` called in `Scheduler.react`. This is *theoretically* necessary since the Trigger object may need to do cleanup / update state, and there is no path *through* it, so the scheduler must use `Trigger._unprime` to signal it. But this function serves a dual purpose of also being the method use to prematurely cancel the Trigger.

I'll work on this in a follow on. What's here is good enough to come in and unblocks further feature work.

**Review by imphil — APPROVED** [review]
LGTM from a code point of view.

On "Don't attempt to reuse value change callbacks": do you have an idea why callbacks were reused before? One could imagine performance being the reason. Were you able to check the performance before and after this change?

**Comment by ktbarrett** [comment]
I traced it back to https://github.com/cocotb/cocotb/commit/ef963f33c976514701abfca060dfc4c475b3c4a9 where it was a single value change callback called `value_cb`. No indication why it was done that way originally.

**Comment by olagrottvik** [comment]
@ktbarrett I have traced a massive performance hit to commit f930bc77f239f4556371a1d5ea4cad8bb2349565. 

In my example the simulation runtime goes from 2.72 s to 48.92 s.

Are you already aware of this? If not, should I create an issue and try to provide a minimal example?

**Comment by ktbarrett** [comment]
@ktbarrett Which simulator? There was an issue that reported a slowdown issue with Questa.

**Comment by olagrottvik** [comment]
Riviera-Pro

I made an issue here: https://github.com/cocotb/cocotb/issues/4379

**Pull request merged**
