### PR TITLE
Pull docs for fork()/scheduler.add() into Sphinx for linking.

### LINKED ISSUE #1176: Improve the docstring for fork()
``fork`` is missing a docstring, and so it doesn't show up in https://cocotb.readthedocs.io/en/latest/library_reference.html.

### PR DESCRIPTION
**Pull request by cmarqu**
Works towards #1176.

### CODE REVIEW

**Comment by ktbarrett** [comment]
Are you adding documentation to `fork` or just the link?

**Comment by eric-wieser** [comment]
@ktbarrett, result is this: https://external-builds.readthedocs.io/html/cocotb/1177/library_reference.html#cocotb.fork

**Comment by cmarqu** [comment]
Kaleb is right though, my commit message is a bit misleading. I'll amend it later.

**Comment by eric-wieser** [comment]
Looks good, thanks

**Pull request merged**
