### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ktbarrett**
Update python version in readme to 3.6+.

### CODE REVIEW

**Comment by marlonjames** [comment]
Stable (v1.5.2) is 3.5+.
We could add a note for current development / master branch being 3.6+ ?

**Comment by ktbarrett** [comment]
The README should reflect the current state of the repo IMO.

**Comment by imphil** [comment]
The README is a bit of a tricky place since many people use it to learn about cocotb, and others use it to install the latest master version. I generally agree that the README should reflect master, but it's easy to confuse users here. How about we reduce the README to a minimum and point to the versioned documentation instead?

**Comment by marlonjames** [comment]
I'm fine with having it reflect the master branch, I was mostly commenting that the line above it says
> The current stable version of cocotb requires:

**Pull request closed without merging**
