### PR TITLE
Add Icarus master on Windows to CI

### PR DESCRIPTION
**Pull request by tpambor**
Add Icarus master on Windows to CI for #1786

### CODE REVIEW

**Comment by tpambor** [comment]
Maybe somebody can help with `allow_failures`. It isn't respected at the moment.

**Comment by tpambor** [comment]
The merge request [steveicarus/iverilog#325](https://github.com/steveicarus/iverilog/pull/325) with the fix required for building iverilog has been merged.

**Comment by cmarqu** [comment]
> Maybe somebody can help with `allow_failures`. It isn't respected at the moment.

In #1959 used a trick by setting `env: ALLOW_FAILURES=yes` and matching this the `allow_failures` section. Not sure yet if this works all the time.

**Comment by tpambor** [comment]
> In #1959 used a trick by setting `env: ALLOW_FAILURES=yes` and matching this the `allow_failures` section. Not sure yet if this works all the time.

Thanks, works like that

**Comment by cmarqu** [comment]
Thanks! The fail is what you want to keep an eye on with this PR, or is this fixed with one of your other open PRs?:
```
libcocotbvpi_icarus:`C:/users/travis/build/cocotb/cocotb/cocotb/libs\libcocotbvpi_icarus.vpl' failed to open using dlopen() because:
    %1 is not a valid Win32 application.
```

**Comment by tpambor** [comment]
> Thanks! The fail is what you want to keep an eye on with this PR, or is this fixed with one of your other open PRs?:
> 
> ```
> libcocotbvpi_icarus:`C:/users/travis/build/cocotb/cocotb/cocotb/libs\libcocotbvpi_icarus.vpl' failed to open using dlopen() because:
>     %1 is not a valid Win32 application.
> ```

This PR tests for the bug in #1786. A fix for this error is implemented in #1787.

**Pull request merged**
