### PR TITLE
Build and smoke-test the sdist in CI

### LINKED ISSUE #3084: CI: Test building of the sdist
We currently produce a sdist, but don't test if it actually builds. The dev tests are installed directly from source, and the release tests are installed from wheels.

We probably don't want a full testing on the sdists, but a simple build test should be added to ensure #3071 doesn't repeat.

### PR DESCRIPTION
**Pull request by imphil**
Prevent packaging errors from slipping through which make the sdist unusable. No full testing is done on the sdist, we continue to do that on the wheels (otherwise we'd have the same CI pipeline twice, with very limited benefit).

Fixes #3084

### CODE REVIEW

**Comment by imphil** [comment]
Action run showing an (intentionally triggered) failure: https://github.com/cocotb/cocotb/actions/runs/3100416305/jobs/5027859588

**Comment by imphil** [comment]
And a passing run: https://github.com/cocotb/cocotb/actions/runs/3103972632/jobs/5029335507

I'm removing the debug commits now.

**Review by marlonjames — APPROVED** [review]
`release_clean` nox session is just for local development? I don't see it used anywhere in CI

**Comment by imphil** [comment]
Yeah, we don't need the clean session in CI since we run on fresh machines every time. But I needed it locally :)

**Pull request merged**
