### PR TITLE
Make sphinx not generate bogus undocumented return type in autoclass

### PR DESCRIPTION
**Pull request by ktbarrett**
This should remove the `Return type: ` statement from the description of `Join`. Apparently Sphinx thinks class definitions have return types that aren't the class type and it's losing its mind attempting to deduce it so we just turn that logic off and do it manually.

### CODE REVIEW

**Comment by marlonjames** [comment]
`Return type:` goes from 77 hits to 16 on the library reference docs page.
In general I like the auto-generated return type info, so maybe as suggested in the sphinx issue we do whatever to override the `Join` autoclass directive causing the issue?

**Comment by ktbarrett** [comment]
@marlonjames [From the issue](https://github.com/sphinx-doc/sphinx/issues/12472#issuecomment-2188255929):

> I'd say it's a bug but I don't really have time (nor the mood) to fix this one.

When we enable docstring checking in ruff, one of the checks includes enforcing the use of `Args`, `Returns`, etc. So we can compensate manually and won't have to worry about missing any since they are checked.

**Comment by ktbarrett** [comment]
Seems like there's no feature for turning off the return type deduction either.

**Comment by marlonjames** [comment]
Looking at the docs again, if we include
`:rtype: type` 
in the docstring we should be able to add back manually the ones we want.
Too bad we can't disable it just for classes where it fails.

**Review by marlonjames — APPROVED** [review]

**Pull request merged**
