### PR TITLE
Remove Python 2 from Travis

### PR DESCRIPTION
**Pull request by ktbarrett**
Had to move some yaml refs over so the diff isn't as clean as you would expect. #1289.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Let's wait for signoff from @imphil on dropping support for 2.7 in master immediately

**Comment by ktbarrett** [comment]
@themperek Wouldn't you want them to run at the same time? I can agree that `PythonLint` is no longer the right name for them though.

**Comment by ktbarrett** [comment]
@eric-wieser If you are worried about disabling the Python2 tests I can add them back in and set them to allow failure.

**Comment by eric-wieser** [comment]
We agreed in the call today to drop python 2.7 from master - so lets put this in

**Pull request merged**
