### PR TITLE
Add missing "-top" parameter to VCS

### PR DESCRIPTION
**Pull request by ni140**
- add missing "-top" parameter to VCS
- replace spaces to tabs

### CODE REVIEW

**Comment by tymonx** [comment]
This is needed for projects that can have multiple compiled top modules. One common example is when project use Quartus simulation primitives. The Quartus lnsim file has dozens of unused modules 😬

**Comment by ni140** [comment]
> Thanks!
> 
> For the next time:
> 
> * Please don't mix cleanups with actual changes. Whenever you are tempted to do a bulleted list in a commit message, you should do multiple commits instead. (They can be in one PR of course.)
> * In the commit message, describe why a change was done. It's obvious from the code change that you add the `-top` parameter, but why is this actually necessary? Again, in this case, it's reasonably obvious, but that's not always the case.

Sorry, first time doing PR on Github.

**Comment by imphil** [comment]
No worries, your contribution is very much appreciated. Thanks for helping out!

**Comment by eric-wieser** [comment]
> Please don't mix cleanups with actual changes.

It seems this cleanup was actually itself a bug: gh-1241

**Pull request merged**
