### PR TITLE
Split VpiCbHdl.cpp (with history)

### PR DESCRIPTION
**Pull request by ktbarrett**
Alternative to #3727. I left the file structure the same as in that commit. This PR would have to be "merged" in (as opposed to "rebase" or "squash") to preserve history or manually merged and pushed by using `git rebase --rebase-merges`. If we didn't care to do that, we should just go with #3727.

### CODE REVIEW

**Review by marlonjames — APPROVED** [review]
I prefer keeping the history and having a few localized merge commits.
Let's see what the others think.

**Review by cmarqu — APPROVED** [review]

**Comment by ktbarrett** [comment]
@imphil Need your assistance. Can't merge this PR because master is protected against "merge"s.

**Comment by imphil** [comment]
>@imphil Need your assistance. Can't merge this PR because master is protected against "merge"s.

I removed the protection until this PR is in. Happy merging!

**Review by imphil — APPROVED** [review]
I would have been fine either way, but it's nice that you gone through the trouble of doing it this way, @ktbarrett!

**Pull request merged**
