### PR TITLE
Fix UnboundLocalError if no tests run 

### PR DESCRIPTION
**Pull request by eric-wieser**
https://travis-ci.org/cocotb/cocotb/jobs/648364866#L2247

This was introduced in 6b6c623.

Also fixes an incorrect test count that counts only the number of tests in the last suite, not the number in all suites.

### CODE REVIEW

**Comment by eric-wieser** [comment]
This works correctly:

https://travis-ci.org/cocotb/cocotb/jobs/648367746#L2242

**Comment by themperek** [comment]
Why CI fails?

**Comment by eric-wieser** [comment]
Not sure, but it's failing with and without this change.

Windows CI is broken again on master, this just makes the error message the bottom a little clearer.

**Comment by themperek** [comment]
It looks like virtualenv has changed.

Can  try to add `- powershell "$CONDA_PATH; conda install virtualenv"` after/before:
https://github.com/cocotb/cocotb/blob/f018c9c645c34cd24ccaf79c05a3a4d8d1b4695e/.travis.yml#L83


Maybe on windows, we need to give up `tox` (it was the case in the past) and just `make test`?

**Comment by eric-wieser** [comment]
Can we merge this first and try that in a separate PR?

**Pull request merged**
