### PR TITLE
Fix regression in TestFactory wrt unique test names

### PR DESCRIPTION
**Pull request by ktbarrett**
Cherry-pick of #2782 w/ test.

### CODE REVIEW

**Comment by ktbarrett** [comment]
Odd that names are different on 3.6... Needs more investigation.

**Comment by imphil** [comment]
I'll wait with the release until we're sure that this fix is the right one. Users needing this fix urgently can always cherry-pick it or install the 1.6 branch.

**Comment by ktbarrett** [comment]
@imphil The names are correct, see [here](https://github.com/cocotb/cocotb/runs/4328028340?check_suite_focus=true#step:25:688), that is the important part that fixes the reported problem.

The test, as I wrote it, is not working. My guess is that what I'm testing didn't work in 1.5 either.

**Comment by imphil** [comment]
For those of you who don't want to dig into the logs: the test failure on Python 3.6.7 is
>  AssertionError: assert {'_my_test'} == {'cYlBrun_testfactory_testvUCT_001', 'cYlBrun_testfactory_testvUCT_002', 'cYlBrun_testfactory_testvUCT_003', 'cYlBrun_testfactory_testvUCT_004'}

**Comment by ktbarrett** [comment]
So the tests wouldn't pass before either. Going to have to modify the test to just check stdout. No clue why this isn't working though...

**Comment by ktbarrett** [comment]
Big dumb. I was testing against the test's Task object instead of the Test function object in the regression manager.

**Review by imphil — APPROVED** [review]
Great, thanks! I got to the same conclusion before I saw the update here :-)

**Pull request merged**
