### PR TITLE
Fix CI for icarus devel on Windows

### PR DESCRIPTION
**Pull request by tpambor**
Missed the changes from #1909 and #1940 on rebasing #1828

### CODE REVIEW

**Comment by tpambor** [comment]
[https://travis-ci.org/github/cocotb/cocotb/jobs/706808026](https://travis-ci.org/github/cocotb/cocotb/jobs/706808026) confirms that it is working

**Comment by themperek** [comment]
@tpambor Thank you! So basically it works but 2 test are NOT failing.

**Comment by eric-wieser** [comment]
Does this mean we don't need any of the trampoline stuff from the other PR?

**Comment by tpambor** [comment]
> @tpambor Thank you! So basically it works but 2 test are NOT failing.

They will be fixed with #1959

**Comment by tpambor** [comment]
> Does this mean we don't need any of the trampoline stuff from the other PR?

No, my comment was about the regression that I introduced with #1828. I verified that it was fixed with this commit by rebasing the other changes on this PR.

**Comment by eric-wieser** [comment]
Ah, the CI run you link to is _not_ the one for this PR, which is at https://travis-ci.org/github/cocotb/cocotb/jobs/706804785

**Pull request merged**
