### PR TITLE
Replace removed Py_InitModule by PyModule_Create in HAL example

### PR DESCRIPTION
**Pull request by mariushegele**
`Py_InitModule` does not exist in python 3.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Looks good, but I can't tell if CI is exercising this

**Comment by themperek** [comment]
Should probably enable testing on CI by setting `MODULE=test_endian_swapper,test_endian_swapper_hal` in the `Makefile`

**Comment by eric-wieser** [comment]
I'm not sure if we allow setting `MODULE` to more than one thing

**Comment by eric-wieser** [comment]
@mariushegele, please can you run on your computer:
```
git push origin 4ff4e3ab13cb799cdf1c02ce011d29ae7c751a51:issue-1292
```

otherwise we will have lost your work.

**Comment by eric-wieser** [comment]
Nevermind, I was able to apply your changes by using the github `.patch` URLs along with `git am`. I've moved your work to #1302.

**Comment by mariushegele** [comment]
Sorry for that, was totally not on purpose. I see how you should never PR from master.

**Pull request closed without merging**
