### PR TITLE
VHPI: Change ReadOnly callback reason

### PR DESCRIPTION
**Pull request by marlonjames**
Change VHPI `ReadOnly` callback reason to address #2749.

### CODE REVIEW

**Comment by marlonjames** [comment]
Questa doesn't support `vhpiCbRepStartOfPostponed` yet.
Riviera also has some issue.

**Comment by imphil** [comment]
Conclusion from today's maintainer meeting: Let's `#ifdef` this change for Questa only for the moment. I opened https://github.com/cocotb/cocotb/issues/2801 to keep track of the other VHPI simulators.

**Review by imphil — COMMENTED** [review]
LGTM with a Questa ifdef.

**Review by imphil — APPROVED** [review]

**Comment by marlonjames** [comment]
Questa 2021.3 doesn't support `vhpiCbRepStartOfPostponed`.

**Comment by imphil** [comment]
All simulators, including Questa, are currently supporting vhpiCbRepEndOfTimeStep (only). I guess that's good enough for now, no matter what the standard ultimately says. So let's leave things as they are and revisit if that's not good enough any more.

**Pull request closed without merging**
