### PR TITLE
GPI cleanups inspired by a stale branch

### PR DESCRIPTION
**Pull request by eric-wieser**
Some cleanups partially inspired by a stale branch of @leftink. See commit messages for details.

### CODE REVIEW

**Comment by ktbarrett** [comment]
@themperek I left a review.


> Is there a reason this style isn't applied universally? My first look at the FLI shows this.
> https://github.com/cocotb/cocotb/blob/1e3740abec858042a3d9f9856636757537c971b6/cocotb/share/lib/fli/FliImpl.h#L51-L53

**Comment by eric-wieser** [comment]
Primarily I just applied it to the pieces I saw. Also, I have no way of testing whether my FLI changes compile.

**Comment by ktbarrett** [comment]
On a phone rn, otherwise I'd look. Is it at least consistent in VPI and VHPI? We can leave FLI for a follow up, which I can do.

**Comment by ktbarrett** [comment]
Tested with Questa 10.7c and no new issues compiling and no new failing tests.

**Pull request merged**
