### PR TITLE
Update tool dependencies in noxfile

### PR DESCRIPTION
**Pull request by imphil**
Update the tools used in the noxfile to keep up with the latest and greatest.

- **Update gcov dependency in noxfile**
- **Update to cibuildwheel 2.17**

### CODE REVIEW

**Comment by ktbarrett** [comment]
Can we get a release build to see cibuildwheel functions?

**Review by ktbarrett — APPROVED** [review]
As long as it works, I'm happy.

**Comment by ktbarrett** [comment]
Looks like gcovr 5.2 doesn't support Python 3.6. More and more is not supporting it. We could hold off on that change until after 2.0 (the last to support 3.6 IMO as RHEL7 is EoL in June).

**Comment by imphil** [comment]
> I think it might be a good idea to add workflow_dispatch so we can manually run builds rather than do DO NOT MERGE commits.

IIRC, you cannot manually trigger commits from branches in a fork, which is where our pull requests tend to (and should) be from.

**Review by ktbarrett — APPROVED** [review]
LGTM. Merge away!

**Pull request merged**
