### PR TITLE
fix suggested by ktbarret for issue #497

### PR DESCRIPTION
**Pull request by mattvenn**
I ran make test before and after the patch. 
I have tests that fail both before and after, but I can't see easily if there are more fails after.

### CODE REVIEW

**Comment by ktbarrett** [comment]
Azure is showing a legitimate failure with this change. I guess we are going to have to come up with a more elegant solution.

**Comment by garmin-mjames** [comment]
Looking into `test_unicode_handle_assignment_deprecated` failure on Active-HDL 11.1 (should be similar to Riviera):

The problem is that iterating over `dut` (in this case **sample_module**) finds `sample_module.stream_in_string` as a `vpiPort`, so the handle becomes `HierarchyObject(sample_module.stream_in_string)`.

If we try to get the handle directly, `vpi_handle_by_name` returns a `vpiStringVar` so the handle becomes `StringObject(sample_module.stream_in_string)`.

Riviera and Active-HDL aren't finding `stream_in_string` using the list of iterators until `vpiPort`:
https://github.com/cocotb/cocotb/blob/fb02018e9b44100a22a43e841d0cd2293cac3627/cocotb/share/lib/vpi/VpiCbHdl.cpp#L565-L597

**Comment by ktbarrett** [comment]
@garmin-mjames That blasted SINGLETON_HANDLES again... I brought this up in the issue. I really think we need to refactor how objects are discovered since they can have multiple types. SINGLETON_HANDLES isn't the real problem (well, it is a problem, but that's a completely different issue), it's the fact we let handles be created with only `vpiPort` or `vpiInterconnectNet`, etc (the net type or errata) rather than associating *all* type information with the object handle.

What I meant when I talked about a more elegant solution in the issue is when we search for subhandles we need to iterate over all related objects using `vpi_iterate`, create handles to objects we find ***with all the types associated with that object*** (net type, portness, constness, etc.), and then cache that object in SINGLETON_HANDLES. 

The big issue here is ***none*** of the FOSS simulators and only some of the commercial simulators implement `vpi_compare_objects` which we would need to implement this.

**Comment by garmin-mjames** [comment]
@ktbarrett, Yeah, ports should probably not be returned as their own handle. `VhpiImpl::create_gpi_obj_from_handle` gets the base type and looks at that, so we always get the signal associated with the port. We might be able to follow the port to the actual:
```cpp
new_handle = vpi_get(vpiLowConn, port_handle);
```
But that can return any expression, so we'd have to investigate further...

**Comment by garmin-mjames** [comment]
For this issue, I think we can fix the new errors by adding `vpiVariables` back into the module iterators so it gets seen before `vpiPort` iteration.

**Comment by ktbarrett** [comment]
@garmin-mjames Want to try that?

@mattvenn Sorry for taking over your PR. We will try to fix your original issue.

**Comment by garmin-mjames** [comment]
@ktbarret it worked on Active-HDL, i'll make a new PR.

**Comment by ktbarrett** [comment]
@mattvenn Thanks for putting this up, it helped us locate an issue with the suggested fix, but we are going to take #2079.

**Pull request closed without merging**
