### PR TITLE
CI: Run against Verilator 5.026

### PR DESCRIPTION
**Pull request by imphil**
Update CI to the latest release version, as usual.

### CODE REVIEW

**Comment by ktbarrett** [comment]
Welp. Maybe it doesn't work. There's also the issues with `--timing`. I don't think we can support v5.026 yet.

**Comment by imphil** [comment]
It was worth a try :smile: I'll do a documentation update for stable/1.9 and leave the rest of the debugging for a potential later patch release.

**Comment by ktbarrett** [comment]
Try this on 1.9. I think 1.9 *may* work. The MacOS test might fail, but that ends up being an environment issue.

**Comment by ktbarrett** [comment]
Closing in favor of #3861.

**Pull request closed without merging**
