### PR TITLE
Do not link with libpython

### PR DESCRIPTION
**Pull request by tpambor**

### CODE REVIEW

**Comment by ktbarrett** [comment]
Unless we add the path to libpython to the library search path before loading libpython3.X.so this won't work (there are multiple ways to accomplish this). It works on Travis Linux with Python 3.8 because the Python is installed to the system, so libpython is in the system library search path. If you used conda, this wouldn't work. There is a treatment of the issues in #1943.

**Comment by tpambor** [comment]
This was a little test related to #1943.

In [`gpi_embed.cpp`](https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/embed/gpi_embed.cpp#L125) libpython is loaded dynamically (`utils_dyn_open(PY_SO_LIB)`) but as it is linked explicitly actually the system will already try to load it when `libcocotb.so` is loaded. Therefore, I think `utils_dyn_open(PY_SO_LIB)` does not really have an effect in loading `libpython`.

In case of #1943, the error on load of `libcocotb.so` is:
`libpython3.7m.so.1.0: cannot open shared object file: No such file or directory.`

If `libpython` is not explicitly linked this error will go away because runtime loading is used but likely a new error will appear:
`..s/cocotb_utils.cpp:69   in utils_dyn_open Unable to open lib libpython3.7m.so: dlopen(libpython3.7m.so, 9): image not found`
[See here in CI](https://travis-ci.org/github/cocotb/cocotb/jobs/707984795#L1724)

#1943 could be closed by doing something like `utils_dyn_open(find_libpython())` or maybe by passing the path via an environment variable. This way `LD_LIBRARY_PATH` and `PATH` could stay untouched. [JuliaPy](https://github.com/JuliaPy/PyCall.jl/blob/master/src/pyinit.jl#L161) is solving it more or less this way.

**Comment by ktbarrett** [comment]
> Therefore, I think `utils_dyn_open(PY_SO_LIB)` does not really have an effect in loading `libpython`.

This is correct, I've seen logs where it failed to load PY_SO_LIB, but cocotb still runs. Doing both load-time and runtime dynamic loading of libpython is unnecessary.

>  [JuliaPy](https://github.com/JuliaPy/PyCall.jl/blob/master/src/pyinit.jl#L161) is solving it more or less this way.

:eyes:

**Comment by ktbarrett** [comment]
[Here](https://gist.github.com/tkf/d980eee120611604c0b9b5fef5b8dae6) is the original source for the `find_libpython` script. It's MIT licensed.

**Comment by themperek** [comment]
Some observations:
1. If one does not link dynamically (second time) some simulators fail (especially commercial) in a very intriguing way see: https://github.com/cocotb/cocotb/pull/1417#issuecomment-587170566

2. To load dynamically `PY_SO_LIB` has to be right and on mac was always some issues. Since I do not have mac is very hard to debug for me.

Some kind for `find_python` function could be a solution. This can also try to resolve #1943.

**Comment by ktbarrett** [comment]
@themperek After looking the issue you were seeing I feel like this is an issue with *how* the loader is loading libpython when it's loaded as a dependency compared to how we are loading with the dlopen call (does the loader not load globally by default?). It is definitely loading the same library; there is no way the library search path is changing between the calls. I need to find some documentation and run some tests.

@tpambor Since I see you are using `find_libpython`, I should mention that I found it useful, so took the liberty of turning it into a standalone package last night and it's now available on [Pypi](https://pypi.org/project/find-libpython/). If it ends up being a solution, we can decide whether to copy it or have it as a dependency.

**Comment by themperek** [comment]
BTW. 
I do not know if this is a good idea/practice but can we call `cocotb-config` from `c` code? This would simplified makefiles and custom flows. @eric-wieser

**Comment by ktbarrett** [comment]
Developing for Windows is a confusing nightmare to me, I'm still learning. Am I correct in understanding that the Windows issues would be resolved with an import library? It would ensure those missing functions are defined as stubs that would runtime load the implementations, right? Is there an import library available for libpython?

**Comment by tpambor** [comment]
> Developing for Windows is a confusing nightmare to me, I'm still learning. Am I correct in understanding that the Windows issues would be resolved with an import library? It would ensure those missing functions are defined as stubs that would runtime load the implementations, right? Is there an import library available for libpython?
> 
> EDIT: turns out what the libpython anaconda package provides _is_ an import library. So maybe on Windows we should be linking against libpython.

An import library is used when the library/program is linked to the DLL implicitly at link time. Here a delay-import library is required which is used for linking to the DLL at run time. It can be created with `dlltool --def libpython3.8.def --output-delaylib libpython3.8.dll.a`. The .def file itself can be created with `gendef libpython3.8.dll > libpython3.8.def`

**Comment by tpambor** [comment]
I think this can be closed with #2268 merged.

**Pull request closed without merging**
