### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by cmarqu**

### CODE REVIEW

**Review by ktbarrett — APPROVED** [review]

**Comment by marlonjames** [comment]
`sys` is no longer used:
https://github.com/cocotb/cocotb/blob/aa849aa6975dea101ddbed512e823c9245f05ff2/cocotb/scheduler.py#L38

**Comment by ktbarrett** [comment]
> OSError: [Errno 28] No space left on device

Seems like the other issue needs to be fixed first.

**Comment by ktbarrett** [comment]
Re-runnning CI.

**Review by imphil — APPROVED** [review]

**Comment by imphil** [comment]
LGTM, thanks!

**Pull request merged**
