### PR TITLE
Make Colin maintainer

### PR DESCRIPTION
**Pull request by imphil**

### CODE REVIEW

**Comment by imphil** [comment]
Colin accepted the offer to become cocotb maintainer. This is to recognize his great contributions to cocotb, especially in the area of documentation.

Can I please get an approving review from our existing maintainers on that?

**Comment by ktbarrett** [comment]
@cmarqu congrats!

**Comment by cmarqu** [comment]
@ktbarrett Thanks!

**Comment by imphil** [comment]
No disagreement, great! Welcome Colin to the group of cocotb maintainers! Please feel free to review and merge any PR you're comfortable reviewing, and let me know if anything is bothering you.

**Pull request merged**
