### PR TITLE
Support not using parenthesis on cocotb.test

### LINKED ISSUE #2731: Allow not using parens on cocotb.test decorator
In many (if not the majority) of cases, users don't need to pass arguments to the test decorator. In this case it would be nice if they didn't need to "call" the decorator.

```python
@cocotb.test  # no call here
async def test_stuff(dut):
    ...
```

Standard library decorator support this (like `lru_cache`), so there is precedence to support this as well.

### PR DESCRIPTION
**Pull request by teobiton**
Added a test case under tests/test_cases/issue_2731.

Fixes #2731

### CODE REVIEW

**Review by ktbarrett — COMMENTED** [review]
Technically the tests don't need to do anything. These should also be integrated into the test_cocotb/test_tests.py suite. The documentation will need updating and a newsfragment (see documentation/README.md) will need to be created.

**Comment by ktbarrett** [comment]
Also an easy way to set up the linting checks to run automatically whenever you make a commit is by installing pre-commit: `pip install pre-commit` and then installing it for the cocotb repo: `pre-commit install`. Now every time you commit, it will run the listing checks.

**Comment by teobiton** [comment]
Hi,

I updated the test case and added the one without parenthesis to the test suite.
I also updated the documentation with a section that introduces the `@cocotb.test` decorator and created a newsfragment.

**Comment by marlonjames** [comment]
You should remove the `issue_2731` test and just keep the `test_cocotb` changes.

**Comment by teobiton** [comment]
Just removed the duplicated test. The linting errors should also be fixed.

**Comment by ktbarrett** [comment]
For some reason, not all the tests are running. Forcing a re-run.

**Pull request merged**
