### PR TITLE
Document new make variables

### LINKED ISSUE #1322: Document Makefile variables passed to C/C++ compiler
https://github.com/cocotb/cocotb/commit/7e48440155e1e589620e8465889c229db582c14f renamed and improved some variables we pass to compilers. We need to document those, and add a release notes entry for renamed items.

### PR DESCRIPTION
**Pull request by ktbarrett**
Adds documentation for user-facing make variables. Fixes #1322.

### CODE REVIEW

**Comment by cmarqu** [comment]
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html says 
> ``LOADLIBES`` is a deprecated (but still supported) alternative to ``LDLIBS``.
so maybe we don't need this one? It's unlikely a user has this set in their environment and expects us to honor it.

**Comment by ktbarrett** [comment]
Thanks for the catch. I had never heard of `LOADLIBES`, but I saw it on the list and decided to add it. I guess never having heard of it should have been a sign.

**Comment by cmarqu** [comment]
I was actually googling for it because I thought it was a typo :)

**Comment by cmarqu** [comment]
Wielding my new power for the first time, thanks!

**Pull request merged**
