### PR TITLE
Fail if the `results.xml` file was not created

### PR DESCRIPTION
**Pull request by eric-wieser**
Should address https://github.com/cocotb/cocotb/issues/1278#issuecomment-570257200

### CODE REVIEW

**Comment by themperek** [comment]
Should one remove exisitng `results.xml` before starting simulator?

**Comment by eric-wieser** [comment]
Hmm, I suppose strictly yes, it should.

**Comment by eric-wieser** [comment]
Ok, here's one failure:

https://travis-ci.org/cocotb/cocotb/jobs/640371381#L2785

**Comment by themperek** [comment]
One can maybe do this one line here: https://github.com/cocotb/cocotb/blob/599b21ba453aa5a047b24dec80f2c475523105cc/cocotb/share/makefiles/Makefile.sim#L79 (not individually for the simulator)

BTW: the `rm` does not work would need to set COCOTB_RESULTS_FILE as an absolute path somehow https://github.com/cocotb/cocotb/blob/599b21ba453aa5a047b24dec80f2c475523105cc/cocotb/share/makefiles/Makefile.sim#L41

**Comment by eric-wieser** [comment]
> One can maybe do this one line here

I thought about that, but it would still mean that `make results.xml` would claim to succeed even when it doesn't, and that other targets that depend on `$(COCOTB_RESULTS_FILE)` will be lied to.

**Comment by eric-wieser** [comment]
I'm not sure I understand the relative paths problem - everything seems to work just fine as is

**Comment by themperek** [comment]
>I'm not sure I understand the relative paths problem - everything seems to work just fine as is

This `rm` does nothing https://github.com/cocotb/cocotb/blob/599b21ba453aa5a047b24dec80f2c475523105cc/cocotb/share/makefiles/Makefile.sim#L41

Since the results.xml is relative to simulator `pwd` (ex. sim_build) and not makefile `pwd`

**Comment by eric-wieser** [comment]
> and not makefile pwd

the makefile is included, so the makefile pwd in `.sim` is the same as the pwd of the test makefile, for instance `cocotb/tests/test_cases/test_exit_error`.

The `test` commands are working just fine, so I can't see why the `rm`  command wouldn't.

**Comment by eric-wieser** [comment]
Remaining failures:

* https://travis-ci.org/cocotb/cocotb/jobs/640394194#L4566 (#1296)
* https://travis-ci.org/cocotb/cocotb/jobs/640394199#L4112 (#1278)

**Comment by themperek** [comment]
Maybe I got things wrong but why this is not enough (not in the individual Makefiles)?

https://github.com/cocotb/cocotb/blob/599b21ba453aa5a047b24dec80f2c475523105cc/cocotb/share/makefiles/Makefile.sim#L79

**Comment by eric-wieser** [comment]
Because that line only runs if i run `make sim`. If I run `make results.xml`, then that line is completely skipped.

**Comment by themperek** [comment]
>Because that rm only runs if i run make sim. If I run make results.xml, then that line is completely skipped.

Yes. Thank you!

**Comment by eric-wieser** [comment]
Just #1278 left to solve, then we can put this in

**Comment by eric-wieser** [comment]
Thanks for helping out here @themperek!

**Pull request merged**
