### PR TITLE
Revert "remove PY_SO_LIB and do not try to load python dynamically"

### PR DESCRIPTION
**Pull request by themperek**
Reverts cocotb/cocotb#1416

It is needed for commercial simulators.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you paste a snippet of the crash log from a commercial simulator?

**Comment by themperek** [comment]
```
# Loading /home/themperek/miniconda/lib/python3.7/site-packages/cocotb/libs/modelsim/libvpi.so
#      -.--ns INFO     cocotb.gpi                         ../embed/gpi_embed.c:71   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
#      -.--ns INFO     cocotb.gpi                         ../gpi/GpiCommon.cpp:104  in gpi_print_registered_impl       VPI registered
Traceback (most recent call last):
  File "/home/themperek/miniconda/lib/python3.7/site-packages/cocotb/__init__.py", line 37, in <module>
    import random
  File "/home/themperek/miniconda/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /home/themperek/miniconda/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyArg_Parse
#      -.--ns ERROR    cocotb.gpi                         ../embed/gpi_embed.c:203  in get_module_ref                  Failed to load Python module "cocotb"
# 
```

**Comment by imphil** [comment]
For reference: A revert can be done with `git revert commitsha`

**Comment by eric-wieser** [comment]
Note also that it can be done directly through the github UI.

**Comment by eric-wieser** [comment]
Possibly relevant: https://bugs.python.org/issue4434

It would be nice to solve this, but reverting is ok in the short-term.

**Comment by themperek** [comment]
Is ok to merge?

**Comment by themperek** [comment]
It seems to work if I do `LD_PRELOAD=.../cocotb/libs/libcocotbvpi_modelsim.so SIM=questa make`

**Pull request merged**
