### PR TITLE
Add per-test logger.

### PR DESCRIPTION
**Pull request by garmin-mjames**
Adds a backwards-compatible per-test logger object by adding a
parameter to the @cocotb.test decorator called 'pass_test_log'.
This parameter is False by default to preserve compatibility with
older tests.

When set to True, in addition to the 'dut' object, a 'test_log'
object is passed to the test function, allowing the use of a test
specific log 'cocotb.test.test_name' rather than only using the
dut._log object.

Also cleaned up some decorator log names.
RunningTest.log now 'cocotb.test.test_name.0x\<ID>'
coroutine.log now 'cocotb.coroutine.coro_name.0x\<ID>'

Example:
```
@cocotb.test(pass_test_log=True)
def test1(dut, test_log):
    test_log.info("Logging to test log!")
```

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for this PR @garmin-mjames! I like the approach, but before merging I'd love to start a bit a wider discussion where we want to go in terms of logging (there are other PRs open, like #707 that I didn't have a chance to look at). Maybe you can start a thread on the mailing list (https://lists.librecores.org/listinfo/cocotb) to outline your requirements and invite others to the discussion as well?

**Comment by cmarqu** [comment]
The big logging PR is #493.

**Comment by eric-wieser** [comment]
This is a nice idea - I'd perhaps suggest using `inspect.signature` / `inspect.getargspec` to detect the presence of the argument rather than have the user request it.

**Comment by eric-wieser** [comment]
A small rebase is needed here

**Comment by eric-wieser** [comment]
What's the advantage of having a per-test logger if only one test is run at a time? Wouldn't `my_log = logging.getLogger('my_log')` be sufficient at the top of your test file?

**Comment by garmin-mjames** [comment]
It associates the log record with the test that is running, rather than using `dut._log` or an externally defined logger as in your suggestion.

**Comment by eric-wieser** [comment]
Is this in the context of a situation where you've done some custom logging configuration?

**Comment by garmin-mjames** [comment]
The eventual goal was the ability to save per-test log statements separately from the main cocotb logging output, but at the time cocotb logging didn't respect the Python logging hierarchy, etc. So it was more work than we wanted to tackle.

In the end we used it for organization and being able to search for log messages from the actual test body.

I also didn't want to use `dut._log`.

**Comment by eric-wieser** [comment]
> and being able to search for log messages from the actual test body.

What do you mean by this?

**Comment by garmin-mjames** [comment]
We wanted a way to filter for log messages that were put in the test itself as a sort of step-by-step (rather than use Python comments), along with logging of comparisons of actual vs expected values. That way we have a log of the steps and the results of the test beyond just a pass/fail.

**Pull request closed without merging**
