### PR TITLE
Add graphviz package to doc build config

### LINKED ISSUE #3449: Documentation: error rendering inheritance diagrams (v1.8.1)
Diagram images not rendering (https://docs.cocotb.org/en/stable/library_reference.html#simulation-object-handles)

cocotb version: v1.8.1

### PR DESCRIPTION
**Pull request by cmarqu**
This makes the 'dot' binary available to sphinx.ext.inheritance-diagrams
See also https://github.com/readthedocs/readthedocs.org/issues/8672

Closes #3449

In addition, remove the `graphviz_output_format = "svg"` setting since this
renders badly (much too big and without scrollbars) with the currently used
package versions (this could be https://github.com/sphinx-doc/sphinx/issues/10117).

### CODE REVIEW

**Comment by cmarqu** [comment]
To review, look at https://cocotb--3457.org.readthedocs.build/en/3457/library_reference.html#simulation-object-handles

**Comment by marlonjames** [comment]
The image is scaled down from `768x207` to `696.4x187.7` in the docs, but the overlay map with click-links to the classes uses the full-scale measurements.
This results in the link areas being offset from the visible class rectangles.

**Comment by cmarqu** [comment]
@marlonjames Seems something like https://github.com/sphinx-doc/sphinx/issues/4865 has crept up again.
I don't feel like reporting and potentially following up on a Sphinx ticket right now, given the state of the SVG problem in https://github.com/sphinx-doc/sphinx/issues/10117.
Just accept the behavior, hoping it will be fixed at some point, or just remove the whole inheritance diagram?

**Comment by marlonjames** [comment]
I would be fine with either removing the `<map>` or leaving it scaled wrong.

**Comment by ktbarrett** [comment]
Not having a clickable overlay is acceptable.

**Comment by cmarqu** [comment]
Strictly speaking, we now don't use `sphinx.ext.inheritance_diagram` and `graphviz` anymore and could remove it from the doc building setup, but I'd still keep it in to easier re-generate the diagram if needed.

**Review by ktbarrett — APPROVED** [review]

**Pull request merged**
