### PR TITLE
Convert most examples to async/await

### PR DESCRIPTION
**Pull request by eric-wieser**
Most of the rest of #1730 

Since this was easy, I think it's valuable to have these examples in `async` form for people learning from them in the next release.

### CODE REVIEW

**Comment by imphil** [comment]
Wow, a 40 percent increase in coverage? Something must be very wrong with our collection mechanism.

**Comment by eric-wieser** [comment]
> Wow, a 40 percent increase in coverage? Something must be very wrong with our collection mechanism.

I think that's just the `/head` vs `/merge` behavior of CI tools striking again.

**Comment by ktbarrett** [comment]
Adder updates are in #1826, and this leaves the `ping_tun_tap` example as it was.

**Comment by eric-wieser** [comment]
`ping_tun_tap` isn't tested by CI, so I figured I'd play it safe.

**Pull request merged**
