### PR TITLE
Revert "Use slots in triggers for speed and memory savings" 

### PR DESCRIPTION
**Pull request by imphil**
This reverts commit 976e0b7ffedc03fdced48d01c6b74f42eceb93ac for     breaking test_dff.
    
See #1033

### CODE REVIEW

**Comment by imphil** [comment]
@eric-wieser can you have a look?

**Comment by cmarqu** [comment]
FWIW, I only discovered the slots problem while investigating a different breakage of ``test_dff`` (#979), which I believe is because I switched this test to use our built-in clock generator which always starts with a ``1``.
#1036 makes this configurable, and another PR (#1044) would make use of that feature.

**Comment by eric-wieser** [comment]
xref #1012

Looking some more, `__slots__` seem worthwhile even if `"__dict__"` is present - so I'd be inclined to go that way instead. PR coming shortly

**Comment by eric-wieser** [comment]
Alternative at #1045, which should preserve the performance gains

**Comment by imphil** [comment]
going with #1045 instead.

**Pull request closed without merging**
