### PR TITLE
Clean up trigger caching.

### PR DESCRIPTION
**Pull request by Fatsie**
This follow perfomance discussion in #1209 and #1211 that came out of it.

The main question is if code should do optimization of trigger usage by caching them a before loop. If yes this PR can be closed without merging. Otherwise likely some optimization may still be needed before merging this PR. For the latter I don't have currently the bandwidth to work on it.

### CODE REVIEW

**Comment by eric-wieser** [comment]
> The main question is if code should do optimization of trigger usage by caching them a before loop.

It's worth noting that this might not only be a performance optimization, but a _readability_ one. The existing code is easier to check that the same signal is being used for every clock edge, as there a fewer words.

**Comment by Fatsie** [comment]
> It's worth noting that this might not only be a performance optimization, but a _readability_ one.

I agree that there may be other reasons than performance for assigning these events to a variable. Although in this case were often the event is only used once in the loop. I guess this is also a matter of taste; I would only do it if you have more than one clock and/or more than one signal.

What I do want to achieve with this patch to get rid of the believe that events have to be cached for performance reasons. Existing code is often used as starting point rather than docs so it should not be reason for creating false believes.

**Comment by imphil** [comment]
I do think this change improves readability. However: do you have performance numbers for this?

**Comment by ktbarrett** [comment]
@eric-wieser I don't really see any reason this needs to be merged. If you agree, please close.

**Comment by ktbarrett** [comment]
This change no longer applies to this repo.

**Pull request closed without merging**
