### PR TITLE
Remove non-ASCII character from README.md

### PR DESCRIPTION
**Pull request by imphil**
It breaks CI on Python 3.5.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Note that if you _want_ a straight quote here, you can still merge this - but we should merge #1557 anyway, and if we do, can keep our curly quote here if we want it.

**Comment by imphil** [comment]
Thanks, you beat me to it! Let's merge #1557 first and then still merge this one. Non-ASCII characters in the README will certainly cause other trouble down the road, there's no good reason for them in there.

**Comment by eric-wieser** [comment]
> there's no good reason for them in there

I'd perhaps argue there's no reason for them _not_ to be in there, python is almost completely utf8 at this point. Still, I'm not going to argue about a few pixels on a `'` :).

Merge or close as you wish.

**Comment by imphil** [comment]
@eric-wieser can you approve this PR please?

**Pull request merged**
